package org.voyager.commons.constants;

public class ParameterNames {
    public static final String QUERY = "query";
    public static final String SOURCE = "source";
    public static final String SKIP_ROW_COUNT = "skipRowCount";
    public static final String SKIP = "skip";
    public static final String LATITUDE = "latitude";
    public static final String LONGITUDE = "longitude";
    public static final String LIMIT = "limit";
    public static final String PAGE = "page";
    public static final String SIZE = "size";
    public static final String CONTINENT = "continent";
    public static final String COUNTRY_CODE = "countryCode";
    public static final String TYPE = "type";
    public static final String AIRLINE = "airline";
    public static final String ROUTE_ID = "routeId";
    public static final String SEARCH_ID = "searchId";
    public static final String PAUSE = "pause";
    public static final String IATA = "iata";
    public static final String FLIGHT_NUMBER = "flightNumber";
    public static final String ID = "id";
    public static final String START = "start";
    public static final String END = "end";
    public static final String ZONE_ID = "zoneId";
    public static final String ON_DAY = "onDay";
    public static final String DAYS_PAST = "daysPast";
    public static final String DEPARTURE_ZDT = "departureZDT";
    public static final String ARRIVAL_ZDT = "arrivalZDT";
    public static final String DEPARTURE_BEFORE = "departureBefore";
    public static final String ARRIVAL_AFTER = "arrivalAfter";
    public static final String ORIGIN = "origin";
    public static final String DESTINATION = "destination";
    public static final String EXCLUDE = "exclude";
    public static final String EXCLUDE_ROUTE = "excludeRoute";
    public static final String EXCLUDE_FLIGHT = "excludeFlight";
    public static final String IS_ACTIVE = "isActive";
    public static final String STATUS = "status";
    public static final String SOURCE_ID = "sourceId";
    public static final String AIRPORTS = "airports";
    public static final String OPERATOR = "operator";
}